apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: github-tests-python-ukqkrkko 
  janus-idp.io/tekton: github-tests-python-ukqkrkko
  backstage.io/kubernetes-id: github-tests-python-ukqkrkko
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: github-tests-python-ukqkrkko
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml